Fix body <script> evaluation
Regression introduced in 5dfc79ee2feba441ea9c9b486009d08336e78d76:

× chrome 77.0.3865.90 on Mac OS X - RenderingTests - evaluates body script elements on each render
    AssertionError: expected null to equal 1
      at RenderingTests.<anonymous>  <src/tests/rendering_tests.ts:96:4>