CI: Synchronize `VisitTests` test case (#576)
* CI: Synchronize `VisitTests` test case

Addresses [flaky `VisitTests` test case][ci-failure]:

```
× chrome on linux - VisitTests - updates HTML element classes (0.301s)
    AssertionError: expected 'html-attributes' to equal 'html-attributes-two'

    A html-attributes
    E html-attributes-two

      at VisitTests.test updates HTML element classes @ src/tests/functional/visit_tests.ts:140:16
      at runMicrotasks @ anonymous
      at processTicksAndRejections @ node:internal/process/task_queues:96:5
      at async VisitTests.runTest @ src/tests/helpers/intern_test_case.ts:43:6

No unit test coverage for chrome on linux
```

The change adds an `await` clause ahead of the
`this.clickSelector("#link")` call to force the driver to complete the
click interaction before proceeding onto the next line.

[ci-failure]: https://github.com/hotwired/turbo/runs/6273537423?check_suite_focus=true

* Extract `getDocumentElementAttribute` test helper

Abstract access to the test document's `document.documentElement` into a
test helper, then use that in-place.

Consistently unify access to the attributes through the `getAttribute`
method, including a replacement of `className` with `"class"`.